### ISSUE TITLE
devtools disconnected

### ISSUE THREAD

**Issue by dodododooo** [Su-yj/class_manage#1]
![image](https://user-images.githubusercontent.com/17663910/99652388-baa68880-2a92-11eb-82b5-71de92d80c24.png)
你好，你这个版本的electron调试的时候会不会遇到这个问题

**Comment by Su-yj** [comment]
@dodododooo 可能是开发的时候修改代码部分比较多，vue需要刷新页面，但是electron内部机制又不会帮你重新渲染造成的吧。试一下重新运行就好了。electron调试还是比较费劲的，不像浏览器直接刷新就可以了。

**Comment by dodododooo** [comment]
> @dodododooo 可能是开发的时候修改代码部分比较多，vue需要刷新页面，但是electron内部机制又不会帮你重新渲染造成的吧。试一下重新运行就好了。electron调试还是比较费劲的，不像浏览器直接刷新就可以了。

找到原因了，[https://github.com/mapbox/node-sqlite3/issues/1370](url)
